# Generated by Django 4.2 on 2024-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Characteristic',
                'verbose_name_plural': 'Characteristics',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'CharacteristicCategory',
                'verbose_name_plural': 'CharacteristicCategories',
            },
        ),
        migrations.CreateModel(
            name='DominantSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Доминирующая рука/нога')),
            ],
            options={
                'verbose_name': 'DominantSide',
                'verbose_name_plural': 'DominantSides',
            },
        ),
    ]
