# Generated by Django 4.2 on 2024-03-25 00:11

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('entitybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthday', models.DateField(help_text='Дата рождения', verbose_name='Дата рождения')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(120)], verbose_name='Вес')),
                ('height', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(210)], verbose_name='Рост')),
                ('about', models.TextField(help_text='Расскажите о себе', verbose_name='О себе')),
                ('dominant_side', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='players.dominantside', verbose_name='Доминирующая рука/нога')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('teams.entitybasemodel',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите позицию', max_length=50, verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='players.player', verbose_name='Игрок')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'TeamPlayer',
                'verbose_name_plural': 'TeamPlayers',
            },
        ),
        migrations.CreateModel(
            name='SportPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_positions', to='players.position', verbose_name='Position')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_positions', to='teams.sport', verbose_name='Sport')),
            ],
            options={
                'verbose_name': 'SporPosition',
                'verbose_name_plural': 'SporPositions',
            },
        ),
        migrations.CreateModel(
            name='SportDominantSide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='players.dominantside', verbose_name='Доминирующая рука/нога')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominant_sides', to='teams.sport', verbose_name='Спорт')),
            ],
            options={
                'verbose_name': 'SportDominantSide',
                'verbose_name_plural': 'SportDominantSides',
            },
        ),
        migrations.CreateModel(
            name='PositionCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_characteristics', to='teams.sport', verbose_name='Спортивня характеристика')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_characteristics', to='players.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'PositionCharacteristic',
                'verbose_name_plural': 'PositionCharacteristics',
            },
        ),
        migrations.CreateModel(
            name='PlayerSportPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_positions', to='players.player')),
                ('sport_postion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.sportposition')),
            ],
            options={
                'verbose_name': 'PlayerSportPosition',
                'verbose_name_plural': 'PlayerSportPositions',
            },
        ),
        migrations.CreateModel(
            name='PlayerPositionCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_characteristics', to='players.player')),
                ('position_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.positioncharacteristic')),
            ],
            options={
                'verbose_name': 'PlayerPositionCharacteristic',
                'verbose_name_plural': 'PlayerPositionCharacteristics',
            },
        ),
        migrations.CreateModel(
            name='PlayerContactDetails',
            fields=[
                ('contactdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.contactdetails')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='players.player', verbose_name='Контактные данные')),
            ],
            bases=('teams.contactdetails',),
        ),
        migrations.AddField(
            model_name='characteristic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='players.characteristiccategory'),
        ),
    ]
