# .github/workflows/main.yml
name: Team_finder main workflow

on:
  push:
    branches:
      - '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      # use flake8==6.0.0 same as we used in YP
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 isort
    - name: Test with flake8
      run: |
        python -m flake8
    - name: Check commit message
      # Check if commit message match pattern TF<number>:<whitespace><description>
      run: |
        COMMIT_MSG="${{ github.event.head_commit.message }}"
        if [[ ! $COMMIT_MSG =~ ^TF[0-9]+:\ .+ ]]; then
          echo "Error: Commit message does not match required format."
          exit 1
        fi
    - name: Auto-correct imports
      # isort --atomic only apply changes if they don't introduce syntax errors
      run: isort --atomic .
    # Commit all changed files back to the repository
    - name: Commit and push auto corrections
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Leave original message for automatic corrections
        commit_message: "${{ github.event.head_commit.message }}"

  